/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PathRouteImport } from './routes/path'
import { Route as PackageRouteImport } from './routes/package'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as DuelsRouteImport } from './routes/duels'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as UUserIdRouteImport } from './routes/u.$userId'
import { Route as OnboardingResultRouteImport } from './routes/onboarding.result'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as GeneratorSlugRouteImport } from './routes/generator.$slug'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout.cancelled'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminAiGeneratorsRouteImport } from './routes/admin.ai-generators'
import { Route as AdminModulesModuleIdRouteImport } from './routes/admin.modules.$moduleId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronStreakWarningRouteImport } from './routes/api/public/cron/streak-warning'
import { Route as ApiPublicCronFinalizeDuelsRouteImport } from './routes/api/public/cron/finalize-duels'
import { Route as ApiPublicCronDailyChallengesRouteImport } from './routes/api/public/cron/daily-challenges'
import { Route as AdminCoursesCourseIdLessonsRouteImport } from './routes/admin.courses.$courseId.lessons'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PathRoute = PathRouteImport.update({
  id: '/path',
  path: '/path',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelsRoute = DuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const UUserIdRoute = UUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingResultRoute = OnboardingResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => OnboardingRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorSlugRoute = GeneratorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GeneratorRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/checkout/cancelled',
  path: '/checkout/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiGeneratorsRoute = AdminAiGeneratorsRouteImport.update({
  id: '/ai-generators',
  path: '/ai-generators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesModuleIdRoute = AdminModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronStreakWarningRoute =
  ApiPublicCronStreakWarningRouteImport.update({
    id: '/api/public/cron/streak-warning',
    path: '/api/public/cron/streak-warning',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFinalizeDuelsRoute =
  ApiPublicCronFinalizeDuelsRouteImport.update({
    id: '/api/public/cron/finalize-duels',
    path: '/api/public/cron/finalize-duels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDailyChallengesRoute =
  ApiPublicCronDailyChallengesRouteImport.update({
    id: '/api/public/cron/daily-challenges',
    path: '/api/public/cron/daily-challenges',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCoursesCourseIdLessonsRoute =
  AdminCoursesCourseIdLessonsRouteImport.update({
    id: '/$courseId/lessons',
    path: '/$courseId/lessons',
    getParentRoute: () => AdminCoursesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/calendar': typeof CalendarRoute
  '/challenges': typeof ChallengesRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/credits': typeof CreditsRoute
  '/duels': typeof DuelsRoute
  '/generator': typeof GeneratorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/package': typeof PackageRoute
  '/path': typeof PathRoute
  '/pricing': typeof PricingRoute
  '/problems': typeof ProblemsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-generators': typeof AdminAiGeneratorsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/generator/$slug': typeof GeneratorSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/onboarding/result': typeof OnboardingResultRoute
  '/u/$userId': typeof UUserIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/courses/$courseId/lessons': typeof AdminCoursesCourseIdLessonsRoute
  '/api/public/cron/daily-challenges': typeof ApiPublicCronDailyChallengesRoute
  '/api/public/cron/finalize-duels': typeof ApiPublicCronFinalizeDuelsRoute
  '/api/public/cron/streak-warning': typeof ApiPublicCronStreakWarningRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/calendar': typeof CalendarRoute
  '/challenges': typeof ChallengesRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/credits': typeof CreditsRoute
  '/duels': typeof DuelsRoute
  '/generator': typeof GeneratorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/package': typeof PackageRoute
  '/path': typeof PathRoute
  '/pricing': typeof PricingRoute
  '/problems': typeof ProblemsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-generators': typeof AdminAiGeneratorsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/generator/$slug': typeof GeneratorSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/onboarding/result': typeof OnboardingResultRoute
  '/u/$userId': typeof UUserIdRoute
  '/courses': typeof CoursesIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/courses/$courseId/lessons': typeof AdminCoursesCourseIdLessonsRoute
  '/api/public/cron/daily-challenges': typeof ApiPublicCronDailyChallengesRoute
  '/api/public/cron/finalize-duels': typeof ApiPublicCronFinalizeDuelsRoute
  '/api/public/cron/streak-warning': typeof ApiPublicCronStreakWarningRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/badges': typeof BadgesRoute
  '/calendar': typeof CalendarRoute
  '/challenges': typeof ChallengesRoute
  '/coach': typeof CoachRoute
  '/community': typeof CommunityRoute
  '/courses': typeof CoursesRouteWithChildren
  '/credits': typeof CreditsRoute
  '/duels': typeof DuelsRoute
  '/generator': typeof GeneratorRouteWithChildren
  '/leaderboard': typeof LeaderboardRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/package': typeof PackageRoute
  '/path': typeof PathRoute
  '/pricing': typeof PricingRoute
  '/problems': typeof ProblemsRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rewards': typeof RewardsRoute
  '/stats': typeof StatsRoute
  '/tasks': typeof TasksRoute
  '/admin/ai-generators': typeof AdminAiGeneratorsRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/generator/$slug': typeof GeneratorSlugRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/onboarding/result': typeof OnboardingResultRoute
  '/u/$userId': typeof UUserIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/courses/$courseId/lessons': typeof AdminCoursesCourseIdLessonsRoute
  '/api/public/cron/daily-challenges': typeof ApiPublicCronDailyChallengesRoute
  '/api/public/cron/finalize-duels': typeof ApiPublicCronFinalizeDuelsRoute
  '/api/public/cron/streak-warning': typeof ApiPublicCronStreakWarningRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advisor'
    | '/auth'
    | '/badges'
    | '/calendar'
    | '/challenges'
    | '/coach'
    | '/community'
    | '/courses'
    | '/credits'
    | '/duels'
    | '/generator'
    | '/leaderboard'
    | '/onboarding'
    | '/package'
    | '/path'
    | '/pricing'
    | '/problems'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/stats'
    | '/tasks'
    | '/admin/ai-generators'
    | '/admin/courses'
    | '/checkout/cancelled'
    | '/checkout/return'
    | '/courses/$courseId'
    | '/generator/$slug'
    | '/lessons/$lessonId'
    | '/onboarding/result'
    | '/u/$userId'
    | '/courses/'
    | '/admin/modules/$moduleId'
    | '/admin/courses/$courseId/lessons'
    | '/api/public/cron/daily-challenges'
    | '/api/public/cron/finalize-duels'
    | '/api/public/cron/streak-warning'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advisor'
    | '/auth'
    | '/badges'
    | '/calendar'
    | '/challenges'
    | '/coach'
    | '/community'
    | '/credits'
    | '/duels'
    | '/generator'
    | '/leaderboard'
    | '/onboarding'
    | '/package'
    | '/path'
    | '/pricing'
    | '/problems'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/stats'
    | '/tasks'
    | '/admin/ai-generators'
    | '/admin/courses'
    | '/checkout/cancelled'
    | '/checkout/return'
    | '/courses/$courseId'
    | '/generator/$slug'
    | '/lessons/$lessonId'
    | '/onboarding/result'
    | '/u/$userId'
    | '/courses'
    | '/admin/modules/$moduleId'
    | '/admin/courses/$courseId/lessons'
    | '/api/public/cron/daily-challenges'
    | '/api/public/cron/finalize-duels'
    | '/api/public/cron/streak-warning'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advisor'
    | '/auth'
    | '/badges'
    | '/calendar'
    | '/challenges'
    | '/coach'
    | '/community'
    | '/courses'
    | '/credits'
    | '/duels'
    | '/generator'
    | '/leaderboard'
    | '/onboarding'
    | '/package'
    | '/path'
    | '/pricing'
    | '/problems'
    | '/products'
    | '/profile'
    | '/reset-password'
    | '/rewards'
    | '/stats'
    | '/tasks'
    | '/admin/ai-generators'
    | '/admin/courses'
    | '/checkout/cancelled'
    | '/checkout/return'
    | '/courses/$courseId'
    | '/generator/$slug'
    | '/lessons/$lessonId'
    | '/onboarding/result'
    | '/u/$userId'
    | '/courses/'
    | '/admin/modules/$moduleId'
    | '/admin/courses/$courseId/lessons'
    | '/api/public/cron/daily-challenges'
    | '/api/public/cron/finalize-duels'
    | '/api/public/cron/streak-warning'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvisorRoute: typeof AdvisorRoute
  AuthRoute: typeof AuthRoute
  BadgesRoute: typeof BadgesRoute
  CalendarRoute: typeof CalendarRoute
  ChallengesRoute: typeof ChallengesRoute
  CoachRoute: typeof CoachRoute
  CommunityRoute: typeof CommunityRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  DuelsRoute: typeof DuelsRoute
  GeneratorRoute: typeof GeneratorRouteWithChildren
  LeaderboardRoute: typeof LeaderboardRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PackageRoute: typeof PackageRoute
  PathRoute: typeof PathRoute
  PricingRoute: typeof PricingRoute
  ProblemsRoute: typeof ProblemsRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RewardsRoute: typeof RewardsRoute
  StatsRoute: typeof StatsRoute
  TasksRoute: typeof TasksRoute
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  UUserIdRoute: typeof UUserIdRoute
  ApiPublicCronDailyChallengesRoute: typeof ApiPublicCronDailyChallengesRoute
  ApiPublicCronFinalizeDuelsRoute: typeof ApiPublicCronFinalizeDuelsRoute
  ApiPublicCronStreakWarningRoute: typeof ApiPublicCronStreakWarningRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path': {
      id: '/path'
      path: '/path'
      fullPath: '/path'
      preLoaderRoute: typeof PathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duels': {
      id: '/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof DuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/u/$userId': {
      id: '/u/$userId'
      path: '/u/$userId'
      fullPath: '/u/$userId'
      preLoaderRoute: typeof UUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/result': {
      id: '/onboarding/result'
      path: '/result'
      fullPath: '/onboarding/result'
      preLoaderRoute: typeof OnboardingResultRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator/$slug': {
      id: '/generator/$slug'
      path: '/$slug'
      fullPath: '/generator/$slug'
      preLoaderRoute: typeof GeneratorSlugRouteImport
      parentRoute: typeof GeneratorRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/checkout/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-generators': {
      id: '/admin/ai-generators'
      path: '/ai-generators'
      fullPath: '/admin/ai-generators'
      preLoaderRoute: typeof AdminAiGeneratorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules/$moduleId': {
      id: '/admin/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/admin/modules/$moduleId'
      preLoaderRoute: typeof AdminModulesModuleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/streak-warning': {
      id: '/api/public/cron/streak-warning'
      path: '/api/public/cron/streak-warning'
      fullPath: '/api/public/cron/streak-warning'
      preLoaderRoute: typeof ApiPublicCronStreakWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/finalize-duels': {
      id: '/api/public/cron/finalize-duels'
      path: '/api/public/cron/finalize-duels'
      fullPath: '/api/public/cron/finalize-duels'
      preLoaderRoute: typeof ApiPublicCronFinalizeDuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/daily-challenges': {
      id: '/api/public/cron/daily-challenges'
      path: '/api/public/cron/daily-challenges'
      fullPath: '/api/public/cron/daily-challenges'
      preLoaderRoute: typeof ApiPublicCronDailyChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/courses/$courseId/lessons': {
      id: '/admin/courses/$courseId/lessons'
      path: '/$courseId/lessons'
      fullPath: '/admin/courses/$courseId/lessons'
      preLoaderRoute: typeof AdminCoursesCourseIdLessonsRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesCourseIdLessonsRoute: typeof AdminCoursesCourseIdLessonsRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesCourseIdLessonsRoute: AdminCoursesCourseIdLessonsRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminRouteChildren {
  AdminAiGeneratorsRoute: typeof AdminAiGeneratorsRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminModulesModuleIdRoute: typeof AdminModulesModuleIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiGeneratorsRoute: AdminAiGeneratorsRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminModulesModuleIdRoute: AdminModulesModuleIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface GeneratorRouteChildren {
  GeneratorSlugRoute: typeof GeneratorSlugRoute
}

const GeneratorRouteChildren: GeneratorRouteChildren = {
  GeneratorSlugRoute: GeneratorSlugRoute,
}

const GeneratorRouteWithChildren = GeneratorRoute._addFileChildren(
  GeneratorRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingResultRoute: typeof OnboardingResultRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingResultRoute: OnboardingResultRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvisorRoute: AdvisorRoute,
  AuthRoute: AuthRoute,
  BadgesRoute: BadgesRoute,
  CalendarRoute: CalendarRoute,
  ChallengesRoute: ChallengesRoute,
  CoachRoute: CoachRoute,
  CommunityRoute: CommunityRoute,
  CoursesRoute: CoursesRouteWithChildren,
  CreditsRoute: CreditsRoute,
  DuelsRoute: DuelsRoute,
  GeneratorRoute: GeneratorRouteWithChildren,
  LeaderboardRoute: LeaderboardRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PackageRoute: PackageRoute,
  PathRoute: PathRoute,
  PricingRoute: PricingRoute,
  ProblemsRoute: ProblemsRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RewardsRoute: RewardsRoute,
  StatsRoute: StatsRoute,
  TasksRoute: TasksRoute,
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  UUserIdRoute: UUserIdRoute,
  ApiPublicCronDailyChallengesRoute: ApiPublicCronDailyChallengesRoute,
  ApiPublicCronFinalizeDuelsRoute: ApiPublicCronFinalizeDuelsRoute,
  ApiPublicCronStreakWarningRoute: ApiPublicCronStreakWarningRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
